SELECT
	*
FROM
	TRIBE;

SELECT
	*
FROM
	"family";

SELECT
	*
FROM
	"subfamily";


SELECT
	*
FROM
	"genus";

SELECT
	*
FROM
	SPECIES;


SELECT
	*
FROM
	OBSERVATION;

SELECT
	*
FROM
	PRESERVATION_METHOD;
	
SELECT
	*
FROM
	ENVIRONMENT;
	
SELECT
	*
FROM
	TRAP

SELECT
	*
FROM
	PERSON;

SELECT
	*
FROM
	IDENTIFIER;


SELECT
	*
FROM
	COLLECTOR;

select * from province;
select * from department;
select * from locality;


SELECT
	O.ID_OBSERVATION,
	C.collection_date,
	PRSN.person_name,
	PRSN.person_lastname,
	TRP.trap_name,
	PM.method_name,
	E.SCIENTIFIC_NAME AS SPECIES,
	G.SCIENTIFIC_NAME AS GENUS,
	T.SCIENTIFIC_NAME AS TRIBE,
	S.SCIENTIFIC_NAME AS SUBFAMILY,
	F.SCIENTIFIC_NAME AS FAMILY,
	P.PROVINCE_NAME AS PROVINCE,
	D.DEPARTMENT_NAME AS DEPARTMENT,
	L.LOCALITY_NAME AS LOCALITY
FROM
	OBSERVATION O
	-- JOINs de collection
	JOIN COLLECTION C ON O.ID_COLLECTION = C.ID_COLLECTION
	JOIN COLLECTOR CLTR ON CLTR.ID_COLLECTOR = C.ID_COLLECTOR
	JOIN PERSON PRSN ON PRSN.ID_PERSON = CLTR.ID_PERSON
	JOIN TRAP TRP ON TRP.ID_TRAP = C.ID_TRAP
	JOIN PRESERVATION_METHOD PM ON  PM.ID_PRESERVATION_METHOD = C.ID_PRESERVATION_METHOD
	-- JOINs de descripcion animal
	JOIN SPECIES E ON O.ID_SPECIES = E.ID_SPECIES
	JOIN GENUS G ON E.ID_GENUS = G.ID_GENUS
	JOIN TRIBE T ON G.ID_TRIBE = T.ID_TRIBE
	JOIN SUBFAMILY S ON T.ID_SUBFAMILY = S.ID_SUBFAMILY
	JOIN FAMILY F ON S.ID_FAMILY = F.ID_FAMILY
	-- JOINs de location
	JOIN LOCALITY L ON O.ID_LOCALITY = L.ID_LOCALITY
	JOIN DEPARTMENT D ON L.ID_DEPARTMENT = D.ID_DEPARTMENT
	JOIN PROVINCE P ON D.ID_PROVINCE = P.ID_PROVINCE;



SELECT
	E.ID_SPECIES,
	E.SCIENTIFIC_NAME AS SPECIES,
	G.SCIENTIFIC_NAME AS GENUS
FROM
	SPECIES E
	JOIN GENUS G ON E.ID_GENUS = G.ID_GENUS;

SELECT
	T.ID_TRIBE,
	T.SCIENTIFIC_NAME AS TRIBE,
	S.SCIENTIFIC_NAME AS SUBFAMILY
FROM
	TRIBE T
	JOIN SUBFAMILY S ON T.ID_SUBFAMILY = S.ID_SUBFAMILY;

SELECT
	S.ID_SUBFAMILY,
	S.SCIENTIFIC_NAME AS SUBFAMILY,
	F.SCIENTIFIC_NAME AS FAMILY
FROM
	SUBFAMILY S
	JOIN FAMILY F ON S.ID_FAMILY = F.ID_FAMILY;

SELECT
	G.ID_GENUS,
	G.SCIENTIFIC_NAME AS GENUS,
	T.SCIENTIFIC_NAME AS TRIBE
FROM
	GENUS G
	JOIN TRIBE T ON G.ID_TRIBE = T.ID_TRIBE;

SELECT
	F.ID_FAMILY,
	F.SCIENTIFIC_NAME AS FAMILY
FROM
	FAMILY F;

SELECT
	L.ID_LOCALITY,
	D.DEPARTMENT_NAME AS DEPARTMENT,
	L.LOCALITY_NAME AS LOCALITY 
FROM
	LOCALITY L
	JOIN DEPARTMENT D ON L.ID_DEPARTMENT = D.ID_DEPARTMENT;

SELECT * FROM public.get_observations(-1, -1);